Handle union types for typed properties and docblocks
schmittjoh/serializer pull request #1330
Opened 2021-07-23 17:06 UTC by dgafka

This handle union types for typed properties and DocBlock type resolver. 

The solution allows for defining union types for above, which was previously failing during cache building phase. 
As union type is non implicit in what we are actually serializing / deserializing, we are not trying to recognize which type user want to use in specific context.

How does serialization works?
Serializing knows which type to use, as it actually holds the value that is going to be serialized. It use that value to infer the type and do the serialization. 

How does deserialization works? 
The deserialization will throw an exception as we can't guess, which type user would like to pick. 
This is a place for improvement. Possible we could introduce custom union deserializing handler, that would decide on his own what class he would like to deserialize too. 

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/schmittjoh/serializer/issues/1282 https://github.com/schmittjoh/serializer/issues/1302
| License       | MIT

2021-07-23 17:07 UTC, dgafka commented
ping @yyaremenko @gam6itko :)

2021-11-13 17:30 UTC, goetas commented
i'm sorry for the delay, @dgafka  could you please rebase this?

2022-02-20 15:14 UTC, dgafka commented
@goetas branch is up to date with master now :) 
I am not sure, how to fix phpstan or phpcs for lower PHP versions, can you do it?

2022-04-23 00:38 UTC, davidwindell commented
Just tested this on our app and can confirm it seems to work well for us.

2022-04-25 07:07 UTC, dgafka commented
Hey @goetas,
Can this be merged? :)

2022-04-26 14:36 UTC, scyzoryck requested changes
@dgafka  - Could you take a look at the code style issues that has been reported by the coding standard, please? I believe they can be fixed automatically by the tool. Also you need to exclude your fixture from PHPStan analysis - as in CI it is running with PHP7.4 that do not support union types.

2022-04-27 16:15 UTC, dgafka commented
@scyzoryck how to fix that:

```
  Line   tests/Metadata/Driver/TypedPropertiesDriverTest.php                                                                                                                            
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  15     ParseError (syntax error, unexpected '|', expecting variable (T_VARIABLE)) thrown while looking for class JMS\Serializer\Tests\Fixtures\TypedProperties\UnionTypedProperties.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                                                                             
  53     ParseError (syntax error, unexpected '|', expecting variable (T_VARIABLE)) thrown while looking for class JMS\Serializer\Tests\Fixtures\TypedProperties\UnionTypedProperties.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols 
```

as excluding it from phpstan analyse does not change a thing:

```
    excludePaths:
        - %currentWorkingDirectory%/src/Annotation/ReadOnly.php
        - %currentWorkingDirectory%/tests/Fixtures/TypedProperties/UnionTypedProperties.php
```

2022-04-27 16:21 UTC, dgafka commented
I've put the test under phpstan ignore too. Tests are passing now.

2022-04-28 21:26 UTC, scyzoryck commented on tests/Metadata/Driver/UnionTypedPropertiesDriverTest.php
> +            $this->markTestSkipped(sprintf('%s requires PHP 7.4', TypedPropertiesDriver::class));
```suggestion
            $this->markTestSkipped(sprintf('%s requires PHP 8.0', TypedPropertiesDriver::class));
```

2022-04-28 21:26 UTC, scyzoryck commented on phpstan.neon.dist
> +        - %currentWorkingDirectory%/tests/Serializer/BaseSerializationTest.php
I will check tomorrow if we can setup differently - it would be better to do not ignore test files.

2022-05-02 10:53 UTC, scyzoryck commented on phpstan.neon.dist
> +        - %currentWorkingDirectory%/tests/Serializer/BaseSerializationTest.php
I didn't find any solution to exclude it. May we can split the tests for PHP8.0 only into separate class and ignore them for PHP7.4 static analytics? Configuration for the jobs can be found here: `.github/workflows/static-analysis.yaml`.

2022-05-05 06:19 UTC, dgafka commented
Extracted separate phpstan analysis for PHP 7.4.
The rest of the versions are running against those files :)

2022-05-09 21:51 UTC, scyzoryck approved these changes
Thanks! Looks good for me! @goetas - Could you take a look, please?

2022-05-11 07:32 UTC, merged