Enum deserialization support
schmittjoh/serializer pull request #1393
Opened 2022-02-09 19:35 UTC by the-toster

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #1392 
| License       | MIT

Please check it, hope this can be accepted. I used undocumented `ReflectionClass::isEnum()` but I hope it will be added to documentation soon.

Also, codesniffer is not support enum syntax, so it report couple errors about fixture enum.

2022-02-15 04:57 UTC, the-toster commented
`ReflectionClass::isEnum()` was added to https://github.com/php/doc-en

2022-05-09 08:49 UTC, simPod approved these changes

2022-05-09 09:02 UTC, simPod requested changes

2022-05-09 09:02 UTC, simPod commented on src/Construction/UnserializeObjectConstructor.php
> +            return (new \ReflectionEnum($type['name']))->getCase($data['name'])->getValue();
Can you add a backed enum test case?

My code requires this change:

```suggestion
            return (new \ReflectionEnum($type['name']))->getCase($data)->getValue();
```

(for

```php
enum FlopNetworkEventType: int
{
    case UPDATE = 1;
    case DELETE = 2;
}
```
)

2022-05-09 09:33 UTC, simPod requested changes

2022-05-09 09:33 UTC, simPod commented on src/Metadata/ClassMetadata.php
> +    public $isEnum = false;
see e.g. `isMap` in this class. It needs to implement the same behaviour for isEnum. Now the caching does not work

2022-05-10 08:22 UTC, simPod commented
This should do https://github.com/the-toster/serializer/pull/1

2022-05-11 08:28 UTC, goetas commented
some feedback in https://github.com/schmittjoh/serializer/pull/1384#issuecomment-1123345019

2022-05-12 19:37 UTC, the-toster commented
I can add deserialization by value, but currently both pure and backed serialized by key (at least according to added test), which is right in my opinion, I reason this way:
1) purpose of serialization - subsequent deserialization
2) complete deserialization possible only in same environment as serialization (same classes should be declared, etc)
3) so, enum key is enough and preferable (because it obey PHP identifier syntax, while value can be much complex and large string)

Ofcourse I can understand use cases when serialized object used in other environment, sending to JS frontend for example, this case can be handled with custom handlers.

2022-05-12 21:19 UTC, simPod commented
TBH IDK. I guess we should try to align with php behaviour https://3v4l.org/YM5gu?

Pure enums use keys. Backed enums use value. 🤷🏾‍♀️

2022-05-15 19:26 UTC, the-toster commented
I checked how it works now, serializer treats enum as regular class, that's why backed & pure deserialized correctly.
So I suggest merged as is (because it have no breaking changes), and then add serialization logic (which with BC anyway), for example from #1384.

2022-06-03 09:17 UTC, simPod commented
Here they used values for backed enums https://github.com/spatie/data-transfer-object/pull/277/files#diff-08e8db6ece41c64a6374a66ebb8df6c9c567919411684dbfc699dc4b7113d734  
I'd use keys for basic enums.

2022-07-28 12:50 UTC, Einenlum commented
It would be nice to first know the exact expected behavior about this feature: I think @goetas wanted to have the possibility to serialize/unserialize by key instead of value (see [here](https://github.com/schmittjoh/serializer/pull/1384#issuecomment-1123345019))? I think it should be optional (and the default behavior would be to serialize/deserialize the value of the Backed Enum). Seems like some people (like @the-toster [here](https://github.com/schmittjoh/serializer/pull/1384#issuecomment-1125341660)) would like the possibility to serialize/unserialize non backed enums. I'm quite against it, but it should be discussed by the community.

Also, do we know what is missing from @the-toster's code to work as expected and to be merged?

I don't have so much time either right now to really get into the code, but I can maybe find some time in the following weeks to dive a bit more into it.

Anyway, **thank you all for your work**. I know OpenSource takes a lot of time and energy :heart:.

2022-07-28 13:20 UTC, enumag commented
The behavior I personally expect is to serialize/deserialize backed enums using their values. Other cases feel more situational so I think it would be best if they were not too complicated to implement in userland code (by implementing a customized SubscribingHandlerInterface or something) but not necessarily supported by the library out of the box.

2022-10-20 21:38 UTC, drakulis commented
Guys, I'm really happy to see this PR. Is there anything which prevents you from merging it and releasing new version of serializer?

@the-toster thank you for this PR!

2023-01-06 20:46 UTC, goetas commented
Done in https://github.com/schmittjoh/serializer/pull/1448

2023-01-06 20:46 UTC, closed without merging