Allow doctrine/annotations 2.0
schmittjoh/serializer pull request #1451
Opened 2023-01-02 18:24 UTC by mbabker

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT

This will allow using the `doctrine/annotations` package's 2.x release with the serializer.  The only B/C issue in https://github.com/doctrine/annotations/blob/2.0.x/UPGRADE.md that looks to impact this package was already addressed by #1447 so there shouldn't be any other problems.

2023-01-03 10:36 UTC, scyzoryck commented
Thanks for contribution! 
Looking at the tests that are running I see something is still blocking this package to be installed even on PHP8.2 🤔 
https://github.com/schmittjoh/serializer/actions/runs/3824447038/jobs/6506598849
```
Cache restored from key: linux-php-8.2.0-highest-f81472160faeef1eaa5801fd054d11c93d351ed53ad42a7eaac0d3147b228a45---ignore-platform-req=php
Info from [https://repo.packagist.org:](https://repo.packagist.org/) #StandWithUkraine
Updating dependencies
Lock file operations: 96 installs, 0 updates, 0 removals
  - Locking dealerdirect/phpcodesniffer-composer-installer (v0.7.2)
  - Locking doctrine/annotations (1.14.2)
```

2023-01-03 12:37 UTC, mbabker commented
It's probably https://github.com/doctrine/phpcr-odm/pull/834 blocking it just on a quick scan over the dependency list.

2023-01-05 22:44 UTC, scyzoryck requested changes
After releasing `doctrine/phpcr-odm` it looks like the only blocker is `phpbench` (not released stable version yet) if fails on loading bootstrap file. @mbabker Could you take a look at it, please? 

```
➜  serializer git:(master) ✗ php vendor/bin/phpunit 
PHPUnit 9.5.27 by Sebastian Bergmann and contributors.

Error in bootstrap script: Error:
Call to undefined method Doctrine\Common\Annotations\AnnotationRegistry::registerLoader()
#0 /Users/scyzoryck/projects/serializer/tests/bootstrap.php(16): PHPUnit\Util\FileLoader::{closure}()
#1 /Users/scyzoryck/projects/serializer/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once('/Users/scyzoryc...')
#2 /Users/scyzoryck/projects/serializer/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/Users/scyzoryc...')
#3 /Users/scyzoryck/projects/serializer/vendor/phpunit/phpunit/src/TextUI/Command.php(565): PHPUnit\Util\FileLoader::checkAndLoad('/Users/scyzoryc...')
#4 /Users/scyzoryck/projects/serializer/vendor/phpunit/phpunit/src/TextUI/Command.php(345): PHPUnit\TextUI\Command->handleBootstrap('/Users/scyzoryc...')
#5 /Users/scyzoryck/projects/serializer/vendor/phpunit/phpunit/src/TextUI/Command.php(112): PHPUnit\TextUI\Command->handleArguments(Array)
#6 /Users/scyzoryck/projects/serializer/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#7 /Users/scyzoryck/projects/serializer/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#8 /Users/scyzoryck/projects/serializer/vendor/bin/phpunit(120): include('/Users/scyzoryc...')
#9 {main}
````

2023-01-05 23:20 UTC, mbabker commented
The bootstrap's updated.

2023-01-05 23:39 UTC, scyzoryck approved these changes
Thanks for contribution. 
Tests with `doctrine/annotations` 2.0 passed too on my local with PHP8.2 
@goetas could you merge it please?

2023-01-06 06:20 UTC, merged

2023-01-06 15:56 UTC, msteltenpool commented
Could a new release/tag be made?

2023-01-06 15:57 UTC, goetas commented
https://github.com/schmittjoh/serializer/releases/tag/3.19.0