Ignore enums in TypedPropertiesDriver
schmittjoh/serializer pull request #1458
Opened 2023-01-10 10:51 UTC by ruudk

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  |no
| Doc updated   |no
| BC breaks?    |no 
| Deprecations? |no
| Tests pass?   | yes
| Fixed tickets | #1457
| License       | MIT

This is handled by the EnumPropertiesDriver.

If the TypedPropertiesDriver sets the type, it will be skipped by the EnumPropertiesDriver and causes deserialization to fail.

2023-01-10 11:03 UTC, ruudk commented
@goetas When you have time, I'd like to know if this is the idea. If so, we should add some tests to guard it. Ideally, the [JsonSerializationTest](https://github.com/schmittjoh/serializer/blob/master/tests/Serializer/JsonSerializationTest.php) also sets up this TypedPropertiesDriver properly.

2023-01-10 18:31 UTC, simPod requested changes
I tried this commit in my project but does not fix the issue. The TypedPropertiesDriver is not hit at all.

This is my constructor

```php
/** @param iterable<Pair<IdValue, EnumType>>|null $a*/
    private function __construct(
        #[Serializer\Type(name: 'iterable<Ds\Pair<IdValue, EnumType>>')]
        public iterable|null $a,
    ) {
    }
```

2023-01-10 18:32 UTC, ruudk commented
AFAIK the TypedPropertiesDriver is only hit when the type is not defined. In your case, it is because there is a Type attribute?

2023-01-12 20:07 UTC, ruudk commented
@goetas Could you assist in how to proceed with this PR? Looking at @simPod's comment, I think we're overseeing something.

2023-01-26 18:54 UTC, ruudk commented
@goetas Hope you're feeling better. Do you have time to help us find the problem here? Is my solution correct?

2023-02-03 05:31 UTC, goetas commented
i have tried to look into this but it is confusing... `EnumPropertiesDriver` is registered before the `TypedPropertiesDriver`, thus this should not be a problem at all... is there a way to reproduce the issue?

2023-02-05 11:05 UTC, closed without merging